# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "thinkpad_acpi" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [
    "intel_pstate=no_hwp"
  ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = "options thinkpad_acpi experimental=1 fan_control=1";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b8404c75-407c-458f-8aae-07acf949c288";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/EECB-ED8F";
      fsType = "vfat";
    };

  fileSystems."/home/jw/projects" =
    { device = "/dev/disk/by-uuid/c433a9f7-8454-4c40-b0ff-895f605a538b";
      fsType = "ext4";
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-sdk
    ];
  };
}
